# Generated by Django 4.1.2 on 2022-11-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=224)),
                ('employee_date_of_birth', models.DateTimeField(verbose_name='date_of_birth')),
                ('employee_date_of_registration', models.DateTimeField(verbose_name='date_of_registration')),
                ('employee_sex', models.CharField(max_length=224)),
                ('employee_email_id', models.EmailField(max_length=224)),
                ('employee_qualifications', models.CharField(max_length=224)),
                ('employee_achievements', models.CharField(max_length=224)),
            ],
        ),
        migrations.CreateModel(
            name='Student_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=224)),
                ('student_date_of_birth', models.DateTimeField(verbose_name='date_of_birth')),
                ('student_date_of_registration', models.DateTimeField(verbose_name='date_of_registration')),
                ('student_sex', models.CharField(max_length=224)),
                ('student_aadhaar_num', models.BigIntegerField()),
                ('student_email_id', models.EmailField(max_length=224)),
                ('student_qualifications', models.CharField(max_length=224)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee_register',
        ),
        migrations.DeleteModel(
            name='Student_register',
        ),
    ]
