# Generated by Django 4.1.2 on 2022-11-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_employee_registration_student_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_registration',
            name='employee_date_of_birth',
            field=models.CharField(max_length=224),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='student_date_of_birth',
            field=models.CharField(max_length=224),
        ),
    ]
