# Generated by Django 4.1.2 on 2022-11-19 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_employee_registration_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_registration',
            name='student_qualifications',
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=224)),
                ('courses', models.CharField(max_length=224)),
                ('output', models.CharField(max_length=224)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student_registration')),
            ],
        ),
    ]
