# Generated by Django 4.1.2 on 2022-11-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_student_registration_student_qualifications_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee_registration',
        ),
    ]
