# Generated by Django 4.1.2 on 2022-11-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_delete_employee_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='choices',
            field=models.IntegerField(default=0),
        ),
    ]
